global:
  scrape_interval: 15s

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['0.0.0.0:9090']

  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets:
        - grafana_ip_in_yml:3000
